// flow-typed signature: ec0b94aeeb74f29dc4b57fc748c77960
// flow-typed version: <<STUB>>/knuth-shuffle_v^1.0.8/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'knuth-shuffle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'knuth-shuffle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'knuth-shuffle/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'knuth-shuffle/example.js' {
  declare module.exports: $Exports<'knuth-shuffle/example'>;
}
declare module 'knuth-shuffle/index' {
  declare module.exports: $Exports<'knuth-shuffle'>;
}
declare module 'knuth-shuffle/index.js' {
  declare module.exports: $Exports<'knuth-shuffle'>;
}
