// flow-typed signature: 45af2a6ab72c73decd4e9850bcbcd613
// flow-typed version: <<STUB>>/react-native-linear-gradient_v^2.4.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-linear-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-linear-gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-linear-gradient/index.android' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-linear-gradient/index.android.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.android'>;
}
declare module 'react-native-linear-gradient/index.ios.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.ios'>;
}
declare module 'react-native-linear-gradient/index' {
  declare module.exports: $Exports<'react-native-linear-gradient'>;
}
declare module 'react-native-linear-gradient/index.js' {
  declare module.exports: $Exports<'react-native-linear-gradient'>;
}
