// flow-typed signature: e151ef103e3e66ea37a188d0af90a5e3
// flow-typed version: <<STUB>>/react-native-testfairy_v^2.9.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-testfairy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-testfairy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-testfairy/index' {
  declare module.exports: $Exports<'react-native-testfairy'>;
}
declare module 'react-native-testfairy/index.js' {
  declare module.exports: $Exports<'react-native-testfairy'>;
}
