// flow-typed signature: 6b6347dac01add1916e37bf065e8c652
// flow-typed version: <<STUB>>/react-element-to-jsx-string_v12/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-element-to-jsx-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-element-to-jsx-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-element-to-jsx-string/dist/AnonymousStatelessComponent' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/formatComplexDataStructure' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/formatProp' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/formatPropValue' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/formatReactElementNode' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/formatTree' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/formatTreeNode' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/mergeSiblingPlainStringChildrenReducer' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/propNameSorter' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/formatter/spacer' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/index' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/options' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/parser/parseReactElement' {
  declare module.exports: any;
}

declare module 'react-element-to-jsx-string/dist/tree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-element-to-jsx-string/dist/AnonymousStatelessComponent.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/AnonymousStatelessComponent'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/formatComplexDataStructure.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/formatComplexDataStructure'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/formatProp.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/formatProp'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/formatPropValue.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/formatPropValue'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/formatReactElementNode.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/formatReactElementNode'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/formatTree.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/formatTree'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/formatTreeNode.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/formatTreeNode'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/mergeSiblingPlainStringChildrenReducer.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/mergeSiblingPlainStringChildrenReducer'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/propNameSorter.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/propNameSorter'>;
}
declare module 'react-element-to-jsx-string/dist/formatter/spacer.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/formatter/spacer'>;
}
declare module 'react-element-to-jsx-string/dist/index.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/index'>;
}
declare module 'react-element-to-jsx-string/dist/options.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/options'>;
}
declare module 'react-element-to-jsx-string/dist/parser/parseReactElement.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/parser/parseReactElement'>;
}
declare module 'react-element-to-jsx-string/dist/tree.js' {
  declare module.exports: $Exports<'react-element-to-jsx-string/dist/tree'>;
}
