// flow-typed signature: 99cbaff84f71579e35e3b5b9bef7fe2f
// flow-typed version: <<STUB>>/react-native-hyperlink_v^0.0.11/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-hyperlink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-hyperlink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-hyperlink/Hyperlink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-hyperlink/Hyperlink.js' {
  declare module.exports: $Exports<'react-native-hyperlink/Hyperlink'>;
}
