# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Performance'

target 'safepsyc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for safepsyc

  target 'safepsycTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'safepsyc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for safepsyc-tvOS

  target 'safepsyc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
