# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Performance'
pod 'Firebase/RemoteConfig'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.1'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'RCTNetwork',
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

target 'safepsyc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for safepsyc


  target 'safepsycTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'safepsyc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for safepsyc-tvOS

  target 'safepsyc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
